### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by wolfgang1** [Caerostris/Van2Shout#23]
I have installed Van2Shout with:
Vanilla forum 2.1.6
The Server and Vanilla are in Italian.
I have an issue with special characters: "ò, à, è, ì, ù". They are displayed as "Ã², Ã , Ã¨, Ã¬, Ã¹ ".

**Comment by wolfgang1** [comment]
I'd like to add that there wasn't that problem with the 1.052 version.

**Comment by Caerostris** [comment]
I have updated the encoding and it should be fixed in 8cfc4c93d7ae363c5d04d4444a65ee27498552e4
